name: Maven project
on:
  push:
    branches: [ "master" ]
    
jobs:
  build-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Collecting source code from github
        uses: actions/checkout@v7.0.0

      - name: Installing Java
        uses: actions/setup-java@v5.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Running Maven project
        run: mvn package
