name: Maven project in self-hosted
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Clone GitHub repository
        uses: actions/checkout@v7.0.0

      - name: Build and Package Maven project
        shell: cmd
        run: mvn package
